name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}] # Обновление каждый день в полночь по UTC
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write # Необходимо для записи сгенерированных изображений в репозиторий
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }} # Использует созданный вами секрет
          base: header, activity, community, repositories, metadata

  
